# Generated by Django 4.2 on 2025-12-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingCompany',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
